/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iventori.View;

import iventori.View.Laporan.PpBarang;
import iventori.View.Laporan.TotsIventaris;
import iventori.View.Master.Barang;
import iventori.View.Master.Users;
import iventori.View.Transaksi.BarangKeluar;
import iventori.View.Transaksi.BarangMasuk;
import iventori.model.Sesi;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     * 
     */
    
   
   
    
    
    public Dashboard() {
        initComponents();
        String username = new Sesi().username;
        String level = new Sesi().level;
        boolean acc = new Sesi().access;
        lblName.setText("Welcome, "+username);
        lblLevel.setText("Level : "+level);
       menuBarang.setEnabled(acc);
       menuUsers.setEnabled(acc);
       menuPpBarang.setEnabled(acc);
       menuTotsInv.setEnabled(acc);
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuBarang = new javax.swing.JMenuItem();
        menuUsers = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuBrgMasuk = new javax.swing.JMenuItem();
        menuBrgKeluar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuPpBarang = new javax.swing.JMenuItem();
        menuTotsInv = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setText("Welcome");
        lblName.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblLevel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLevel.setText("Level ");

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jMenu1.setText("Master");

        menuBarang.setText("Barang");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        jMenu1.add(menuBarang);

        menuUsers.setText("Users");
        menuUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsersActionPerformed(evt);
            }
        });
        jMenu1.add(menuUsers);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        menuBrgMasuk.setText("Barang Masuk");
        menuBrgMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBrgMasukActionPerformed(evt);
            }
        });
        jMenu2.add(menuBrgMasuk);

        menuBrgKeluar.setText("Barang Keluar");
        menuBrgKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBrgKeluarActionPerformed(evt);
            }
        });
        jMenu2.add(menuBrgKeluar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        menuPpBarang.setText("Barang Masuk Keluar");
        menuPpBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPpBarangActionPerformed(evt);
            }
        });
        jMenu3.add(menuPpBarang);

        menuTotsInv.setText("Total Nilai Iventaris");
        menuTotsInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTotsInvActionPerformed(evt);
            }
        });
        jMenu3.add(menuTotsInv);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(lblLevel)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsersActionPerformed
        // TODO add your handling code here:
        new Users().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuUsersActionPerformed

    private void menuPpBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPpBarangActionPerformed
        // TODO add your handling code here:
        new PpBarang().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_menuPpBarangActionPerformed

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        // TODO add your handling code here:
        new Barang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBarangActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JOptionPane.showMessageDialog(null,"Logout Berhasill");
        new Login().setVisible(true);
       
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void menuTotsInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTotsInvActionPerformed
        // TODO add your handling code here:\
       new TotsIventaris().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_menuTotsInvActionPerformed

    private void menuBrgMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBrgMasukActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new BarangMasuk().setVisible(true);
        
    }//GEN-LAST:event_menuBrgMasukActionPerformed

    private void menuBrgKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBrgKeluarActionPerformed
        // TODO add your handling code here:
        new BarangKeluar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBrgKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuBrgKeluar;
    private javax.swing.JMenuItem menuBrgMasuk;
    private javax.swing.JMenuItem menuPpBarang;
    private javax.swing.JMenuItem menuTotsInv;
    private javax.swing.JMenuItem menuUsers;
    // End of variables declaration//GEN-END:variables
}
